Particle Filter Implementation
jmtc7/navigation2 pull request #7
Opened 2021-10-25 20:23 UTC by Marwan99

2021-11-15 22:11 UTC, khaled-98 requested changes

2021-11-15 22:11 UTC, khaled-98 commented on nav2_localization/src/plugins/solvers/particle_filter_base.cpp
> +void ParticleFilter::resample()
Add a comment to discuss if this the best place for this to be implemented

2021-11-15 22:11 UTC, khaled-98 commented on nav2_localization/src/plugins/solvers/particle_filter_base.cpp
> +  double c = particles_[0].weight_;
Please update c, u, r and m to clarify what they do

2021-11-15 22:11 UTC, khaled-98 commented on nav2_localization/src/plugins/solvers/particle_filter_base.cpp
> +    mean_yaw += particle.weight_ * yaw;
Please fix the mean yaw

2021-11-15 22:13 UTC, khaled-98 commented on nav2_localization/src/plugins/solvers/mcl_solver.cpp
> +  if (delta_x * delta_x + delta_y * delta_y > 0.01 || delta_yaw > 0.25) {
Take abs value of delta_yaw

2021-11-15 23:07 UTC, Marwan99 commented on nav2_localization/include/nav2_localization/nav2_localization.hpp
> +  void sensorsReceived(
How about scanWithOdomRecieved or similar? And do something similar with  the laser callback. Just to accurately reflect whats happening.

2021-11-15 23:57 UTC, Marwan99 commented on nav2_localization/src/plugins/solvers/particle_filter_base.cpp
> +  particles_poses_pub_ = node_->create_publisher<geometry_msgs::msg::PoseArray>(
Added comment in a different place.

2021-11-17 20:30 UTC, khaled-98 approved these changes

2021-11-17 21:04 UTC, khaled-98 approved these changes

2021-11-17 21:07 UTC, khaled-98 approved these changes

2021-11-17 21:28 UTC, merged